General components
tahmasious/MyMovie-Vue.js pull request #1
Opened 2023-07-07 20:14 UTC by tahmasious

I've implemented main components (those which are used many times).
check the trello board out form more information : 
[boards link](https://trello.com/b/58litasE/kanban-template)

2023-07-08 11:02 UTC, amRashidi requested changes

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/.env
> +VITE_API_READ_ACCESS_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1ZTFlZGU1ZWZmZDI3MGY5YzA2ZGZjYmNiYzA5NTFjZSIsInN1YiI6IjY0NjY1MDZlYzM1MTRjMDExZGM5YzAyNyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.SGUU
add .env file to git ignore (use .env.example)
(VITE_API_READ_ACCESS_TOKEN=your token!!!)

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/App.vue
> +  <!-- <SideBarMoiveCard title="sag" coverImage="../src/assets/TLOU.jpg" :genres="['hello', 'pass']"></SideBarMoiveCard> -->
remove comments

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/App.vue
> +const res = client('https://api.themoviedb.org/3/movie/popular?language=en-US&page=1');
use base url

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/components/general/AddToWatchListBtn.vue
> +        src="../../assets/plus.png"
globalize url (@/)

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/components/general/AddToWatchListBtn.vue
> +    :style="{paddingTop : py, paddingBottom: py, paddingRight: px, paddingLeft: px}"
why??

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/components/general/ImbdContainer.vue
> +  background-color: rgba(255, 255, 255, 0.1);
bg-white background-opacity-10

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/components/general/LogoContainer.vue
> +        <img src="../../assets/logo.png" alt="mymovie logo" class="logo" />
address

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/components/general/LogoContainer.vue
> +.logo {
tailwind class

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/components/general/LogoContainer.vue
> +.logo-container h1 {
same

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/components/general/MainLeftSideBar.vue
> +          <h2 class="nav-section-header">Personal</h2>
do this by v-for

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/components/general/MainLeftSideBar.vue
> +import tahmasiousPhoto from '../../assets/tahmasious.jpg'
address

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/components/general/MainRightSideBar.vue
> +import {client} from './../../utils.js'
address

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/components/general/MainRightSideBar.vue
> +const secRes = client('https://api.themoviedb.org/3/movie/upcoming');
base url

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/components/general/MainRightSideBar.vue
> +const res = client('https://api.themoviedb.org/3/movie/top_rated');
base url

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/components/general/MainRightSideBar.vue
> +  upcomingMoives.value = data.results.slice(0,3);
what if data length is lower than 3?

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/components/general/MainRightSideBar.vue
> +aside {
as i see this style is has repeated all over the sections.
please create a custom global class for this

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/components/general/NavBarItem.vue
> +  console.log(importPathActive);
remove log

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/components/general/NavBarItem.vue
> +  const importPath = `../../assets/${props.title}.png`;
address

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/components/general/NavBarItem.vue
> +  const importPathActive = `../../assets/${props.title}-active.png`;
address

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/components/general/SideBarMoiveCard.vue
> +            alt=""
fill wth title

2023-07-08 11:02 UTC, amRashidi commented on MyMovie/src/utils.js
> +    const res = await client('https://api.themoviedb.org/3/genre/movie/list');
base url

2023-07-09 14:57 UTC, tahmasious commented on MyMovie/src/components/general/AddToWatchListBtn.vue
> +    :style="{paddingTop : py, paddingBottom: py, paddingRight: px, paddingLeft: px}"
@amRashidi 
I didn't understand the problem

2023-07-09 17:43 UTC, tahmasious commented
Merge main component branch to main

2023-07-09 17:43 UTC, merged